routes:
  - path: /apply
    contract: application-intake
    api:
      domain: applications
      create: createApplication
    type: detail

  - path: /cases
    contract: application-case-list
    api:
      domain: applications
      list: listApplications
    type: list

  - path: /cases/:applicationId
    contract: application-caseworker-review
    api:
      domain: applications
      get: getApplication
      update: updateApplication
    type: detail
